### ISSUE TITLE
Get-ConflenceSpaces doesn't work

### ISSUE THREAD

**Issue by jlusky** [lipkau/PsConfluence#4]
Looks like this is due to ConvertFrom-Xml getting called in two places,  Similar to https://github.com/lipkau/PsConfluence/commit/22305d4e7f657aac70f59a226d1d9b01cd4d7351

PS C:\Scripts> Get-ConfluenceSpaces
ConvertFrom-Xml : Cannot process argument transformation on parameter 'InputObject'. Cannot convert value
"System.Object[]" to type "System.Xml.XmlDocument". Error: "The specified node cannot be inserted as the valid child
of this node, because the specified node is the wrong type."
At C:\Program Files\WindowsPowerShell\Modules\PsConfluence\XML-RPC\Spaces.ps1:54 char:40
+                 return ConvertFrom-Xml (Invoke-ConfluenceCall -Url $apiURi -Meth ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Xml], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,ConvertFrom-Xml

**Comment by lipkau** [comment]
Thank you for reporting this. 
I will fix this today.

**Comment by lipkau** [comment]
Fixed with release https://github.com/lipkau/PsConfluence/releases/tag/v1.1.2.0 (ce8e614a96afc70e4ac4c2e5310e8b4d3d80c878).
Updated https://www.powershellgallery.com/packages/PsConfluence
