### ISSUE TITLE
Add-ConfluenceSpacePermissions fails with single permission 

### ISSUE THREAD

**Issue by jlusky** [lipkau/PsConfluence#5]
java.lang.NoSuchMethodException: com.sun.proxy.$Proxy2452.addPermissionToSpace(java.lang.String, Java.util.Vector,
java.lang.String, java.lang.String)

Problem seems to be passing a Vector instead of a String for the 2nd arg.  This hack worked for me:
                    Invoke-ConfluenceCall -Url $apiURi -MethodName "confluence2.addPermissionToSpace" -Params ($token, $Permissions[0], $RemoteEntityName, $SpaceKey)

**Comment by lipkau** [comment]
thank you for reporting this.
I fixed it with version **1.1.2.1**
