### ISSUE TITLE
Permission ValidateSets missing REMOVEOWNCONTENT

### ISSUE THREAD

**Issue by jlusky** [lipkau/PsConfluence#6]
Add-ConfluenceSpacePermissions and Add-ConfluenceSpacePermissions are missing in the REMOVEOWNCONTENT permission in their input validation.

**Comment by jlusky** [comment]
Add-ConfluenceSpacePermissions, Get-ConfluenceSpacePermissions, and Remove-ConfluenceSpacePermissions

**Comment by lipkau** [comment]
Hi @jlusky .

Where did you find that permission?
The [official docs](https://developer.atlassian.com/confdev/deprecated-apis/confluence-xml-rpc-and-soap-apis/remote-confluence-methods#RemoteConfluenceMethods-Permissions.1) don't say anything about that permission.
Further, I ran `Get-ConfluenceAvailableSpacePermissions` on my 5.9.9 installation and didn't find _REMOVEOWNCONTENT_.

**Comment by jlusky** [comment]
It's new in 5.10 I think.  I'm running 6.0.4

On April 4, 2017 12:52:38 AM EDT, Oliver Lipkau <notifications@github.com> wrote:
>Hi @jlusky .
>
>Where did you find that permission?
>The [official
>docs](https://developer.atlassian.com/confdev/deprecated-apis/confluence-xml-rpc-and-soap-apis/remote-confluence-methods#RemoteConfluenceMethods-Permissions.1)
>don't say anything about that permission.
>Further, I ran `Get-ConfluenceAvailableSpacePermissions` on my 5.9.9
>installation and didn't find _REMOVEOWNCONTENT_.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/lipkau/PsConfluence/issues/6#issuecomment-291392955

-- 
Sent from my SunOS 4.1.3_U1 mobile device with elm2.4. Please excuse my brevity.

**Comment by lipkau** [comment]
I was not able to find this permissions in confluence with version < 6.
As I am going to deprecate this Module soon (I will not support Confluence 6+) in favor of [ConfluencePS](https://github.com/brianbunke/ConfluencePS/), I suggest you fork this repo any add it yourself **or** wait until _ConfluencePS_ supports this (which I intend to be not too far into the future)

**Conclusion**: This will not be added to this module. I hope you understand.

**Comment by jlusky** [comment]
ConfluencePS seems to use the REST API, and the REST API doesn't support setting Space permissions yet.  That's the only reason I'm using PsConfluence.

**Comment by lipkau** [comment]
I see.

If you can show me the documentation of this permission flag, I will add it to the function.
